### ISSUE TITLE
How can i get vertex indices of markers in other SMPL models?

### ISSUE THREAD

**Issue by markkim1115** [yz-cnsdqz/MOJO-release#4]
Hi. thanks for your code sharing. it is great work.

I wonder how i can get markers' vertex indices in SMPL or SMPL-H.

Thanks.

**Comment by yz-cnsdqz** [comment]
The provided marker indices are only based on SMPL-X. 
For other body models, or for getting your own marker settings on SMPL-X, you could either annotate them manually, or contact the team of AMASS (https://amass.is.tue.mpg.de).

**Comment by markkim1115** [comment]
Thanks. I'll try it!
